<!DOCTYPE html>
<html lang="de"> 
<head>
<title>TITEL</title>
<meta charset="UTF-8">
<base url="http://dinner.local.sebastianleitz.de/">
<link rel="stylesheet" media="screen, projection, tv" href="/css/screen.css">
</head>
<body>

<header>

<img src="/files/dhbw-logo.png">

<?php if(count($this->messages)): ?>
<div class="messages">
<ul>
<?php foreach($this->messages as $message): ?>
<li><?php echo $message; ?></li>
<?php endforeach; ?>
</ul>
</div>
<?php endif; ?>

<nav>
<ul>
<li>Startseite</li>
<li>Abmelden</li>
</ul>
</nav>
</header>

<?php echo $this->layout()->content ?>

</body>
</html>
