<section id="left">
<article class="box green">
<h2>Gemeinsam kochen</h2>
<div class="content">

<?php if($this->confirmed): ?>

<p>Du kochst mit <?php echo $this->partner->getFirstname(); ?> <?php echo $this->partner->getLastname(); ?>.</p>
<p>Bitte wählt einen Team-Namen aus und entscheidet euch für eine Küche.</p>

<?php echo $this->form; ?>

<?php else: ?>

<?php if($this->owner): ?>

<p>Dein angefragter Partner muss noch bestätigen, dass ihr wirklich ein Team werdet.</p>
<p>Bitte deinen Partner, auf den Link in der E-Mail von uns zu klicken, die wir an ihn verschickt haben.</p>

<?php else: ?>

<p><?php echo $this->partner->getFirstname(); ?> <?php echo $this->partner->getLastname(); ?> möchte mit dir an dieser Veranstaltung teilnehmen.</p>
<p>Bitte wähle eine der folgenden Optionen:</p>

<ul>
<li><a href="<?php echo $this->url(array('controller'=>'event','action'=>'index','id'=>$this->eventId,'partner'=>'yes'), null, FALSE); ?>">Ja, da mache ich mit.</a></li>
<li><a href="<?php echo $this->url(array('controller'=>'event','action'=>'index','id' => $this->eventId,'partner'=>'no'), null, FALSE); ?>">Nein danke.</a></li>
</ul>

<?php endif; ?>

<?php endif; ?>

</div>
</section>
<section id="right">
<article>
<h1>Fester Teampartner</h1>
<p>Du hast ausgewählt, mit einem festen Partner an der Veranstaltung teilzunehmen.</p>
</article>
<article class="box orange">
<h2>Der weitere Ablauf</h2>
<div class="content">
<ol>
<li>Partner mithilfe des Namens suchen</li>
<li>Der Wunschpartner erhält deine Anfrage per E-Mail und muss dich als Partner bestätigen</li>
<li>Einen Teamnamen festlegen</li>
<li>Auswählen, in wessen Wohnung ihr kochen wollt</li>
<li>Nun seid ihr <strong>fertig</strong>, wir sind dran!</li>
<li>Kurz vor der Veranstaltung erhaltet ihr per E-Mail den Hinweis, dass euer Dinner-Fahrplan fertig ist.</li>
<li>Die Adressen, bei denen ihr eingeladen seid, findet ihr dann auf dieser Seite.</li>
</ol>
<p>Sollten Probleme bei diesem Prozess auftreten, schickt uns bitte eine E-Mail!</p>
</div>
</article>
</section>