<section id="left" class="login">
<article>
<h1>Studi-Dinner 2.0</h1>
<p>Am <strong>6.6.</strong> findet das zweite Studi-Dinner an der DHBW Stuttgart statt (nicht wundern, falls ihr den Namen nicht kennt, wir mussten ihn leider ändern).</p>
<p>Für Uneingeweihte: Ihr meldet euch als Zweierteam an und sorgt an dem nämlichen Abend entweder für Vorspeise, Hauptgang oder Dessert – zu Gast bekommt ihr zwei euch hoffentlich vollkommen <strong>fremde Teams</strong>. Die anderen beiden Gänge servieren euch wiederum vollkommen fremde Gastgeber irgendwo in Stuttgart – ihr erhaltet lediglich die Adresse, zu der ihr kommen müsst. Mit etwas Glück lernt ihr so <strong>12 neue Menschen</strong> kennen!</p>
<p><strong>Neu!</strong> Ihr könnt euch auch alleine anmelden, und wir losen euch im Vorfeld einen Kochpartner zu – so könnt ihr sogar <strong>13</strong> neue Personen kennenlernen und der Abend wird noch viel lustiger!</p>
<p>Viel Spaß wünscht euch euer <strong>Dinner-Team</strong> von der Studierendenvertretung!</p>
</article>
</section>

<section id="right" class="login">
<article class="box orange">
<h2>Ablauf</h2>
<div class="content">
<ol>
<li>Registrieren (orange Box auf der Startseite)</li>
<li>Bestätigungslink in der E-Mail klicken (vielleicht im Spam-Ordner?)</li>
<li>Anmelden mit dem grünen Formular</li>
<li>Nach der Anmeldung: <strong>Allergien, Abneigungen, Unverträglichkeiten</strong> im grünen Formular angeben!</li>
<li>Gewünschte Veranstaltung auswählen (orange Box)</li>
<li>Entweder:
    <ul>
    <li>Partner mithilfe des Namens suchen</li>
    <li>Der Wunschpartner erhält deine Anfrage per E-Mail und muss dich als Partner bestätigen</li>
    </ul>
</li>
<li>Oder:
    <ul>
    <li>Zufälligen Partner zuweisen lassen</li>
    <li>Ca. eine Woche vor der Veranstaltung losen wir die Partner zu</li>
    </ul>
</li>
<li>Einen Teamnamen festlegen</li>
<li>Auswählen, in wessen Wohnung ihr kochen wollt</li>
<li>Nun seid ihr <strong>fertig</strong>, wir sind dran!</li>
<li>Kurz vor der Veranstaltung erhaltet ihr per E-Mail den Hinweis, dass euer Dinner-Fahrplan fertig ist.</li>
<li>Die Adressen, bei denen ihr eingeladen seid, findet ihr dann auf dieser Seite.</li>
<li>Guten Appetit!</li>
</ol>
<p><a class="button" href="<?php echo $this->url(array('controller'=>'index','action'=>'index'), null, FALSE); ?>">Jetzt aber anmelden!</a></p>
</div>
</article>
</section>