<section id="left">
<article class="box green">
<h2>Gemeinsam kochen</h2>
<div class="content">
<p>Wenn dir jemand über den Weg läuft, mit dem zu doch noch spontan ein Team bilden möchtest, kannst du deinen zufälligen Partner hier „abbstellen“.</p>
<p><a class="button" href="<?php echo $this->url(array('controller'=>'event','action'=>'partnersuche','divorce'=>true), null, FALSE); ?>">Ich möchte mich doch festlegen!</a><br><small>Dieser Schritt ist nicht mehr möglich, sobald wir die Auslosung vorgenommen haben.</small></p>

</div>
</section>
<section id="right">
<article>
<h1>Zufälliger Teampartner</h1>
<p>Du hast ausgewählt, einen zufälligen Kochpartner zugelost bekommen zu wollen.</p>
</article>
<article class="box orange">
<h2>Der weitere Ablauf</h2>
<div class="content">
<ol>
<li>Auswählen, dass du einen zufälligen Partner haben möchtest</li>
<li>Nun bist du <strong>fertig</strong>, wir sind dran!</li>
<li>Ca. eine Woche vor der Veranstaltung bekommst du per E-Mail den Hinweis, dass die Auslosung abgeschlossen ist.</li>
<li>Hier findest du dann die Kontaktdaten deines Partners und ihr könnt euch absprechen.</li>
<li>Kurz vor der Veranstaltung erhaltet ihr per E-Mail den Hinweis, dass euer Dinner-Fahrplan fertig ist.</li>
<li>Die Adressen, bei denen ihr eingeladen seid, findet ihr dann auf dieser Seite.</li>
</ol>
<p>Sollten Probleme bei diesem Prozess auftreten, schickt uns bitte eine E-Mail!</p>
</div>
</article>
</section>