<section id="left">
<article class="box green">
<h2>Ein Team bilden</h2>
<div class="content">

<p>Wenn dein Partner registriert ist, kannst du ihn hier mit <strong>vollem Vor- und Nachnamen</strong> in dieser Reihenfolge suchen. Wenn du keine Fehler bei der Eingabe machst, sollte das System ihn finden und dein Partner erhält eine E-Mail, die ihn auffordert, deiner Anfrage nachzukommen.</p>
<p>Sobald die Anfrage akzeptiert wurde, kann jeder von euch beiden im nächsten Schritt die Team-Informationen eingeben und ändern.</p>

<?php echo $this->form; ?>

</div>
</section>
<section id="right">
<article>
<h1>Einen Partner suchen</h1>
<p>Für besonders extrovertierte DHBW-Studierende haben wir uns etwas neues überlegt: Die <strong>Dinner-Partnerbörse*</strong>!</p>
<p>Du meldest dich alleine an, und wir losen dir eine weitere Person zu. Zusammen trefft ihr euch im Vorfeld, lernt euch kennen und plant eure Küchenkreation. Wir versuchen, die Auslosung ca. zwei Wochen vor dem 6.6. vorzunehmen, sodass ihr genügend Zeit habt, das in Angriff zu nehmen – und selbstverständlich erhaltet ihr weit mehr Daten voneinander als die Teams untereinander, zum Beispiel Namen und Telefonnummern.</p>
<p><small>* Natürlich handelt es sich nicht um eine Partnerbörse! Weder können wir eure sexuelle Ausrichtung noch sonstige Neigungen berücksichtigen…</small></p>
</article>
<article class="box orange">
<h2>Auf Partnersuche gehen</h2>
<div class="content">
<p><a class="button" href="<?php echo $this->url(array('controller'=>'event','action'=>'partnersuche'), null, FALSE); ?>">Ja, ich will!</a>&nbsp;&nbsp;&nbsp;<small>&nbsp;Wir übernehmen keine Garantie für Symphatie.</small></p>
</div>
</article>
</section>